<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Activation Key' => '',
  'Add another Membership' => '',
  'Add another Payment' => '',
  'Add another Usergroup' => '',
  'Add new' => '',
  'Advanced Search' => '',
  'Avatar' => '',
  'BASIS' => '',
  'BUSINESS' => '',
  'Back' => '',
  'Body' => '',
  'Cancel' => '',
  'Category|Categories' => '',
  'Content' => '',
  'Create' => '',
  'Create Time' => '',
  'Created At' => '',
  'Description' => '',
  'Email' => '',
  'Fields with' => '',
  'Group|Groups' => '',
  'ID' => '',
  'In Blog' => '',
  'In Frontpage' => '',
  'Index' => '',
  'Invalid request. Please do not repeat this request again.' => '',
  'Last Visit' => '',
  'List' => '',
  'Manage' => '',
  'Name' => 'Nombre',
  'None' => '',
  'PageCategory|PageCategories' => '',
  'Page|Pages' => '',
  'Password' => '',
  'PostCategory|PostCategories' => '',
  'Post|Posts' => '',
  'Publication Date' => '',
  'Role|Roles' => '',
  'Search' => '',
  'Slug' => '',
  'Status' => '',
  'The requested page does not exist.' => '',
  'Title' => '',
  'Update' => '',
  'Username' => '',
  'User|Users' => '',
  'View' => '',
  'Visits' => '',
  'Your request is invalid.' => '',
  'are required' => '',
  'index' => '',
  'password' => '',
  '{$label}' => '',
  '{relation}' => '',
    'Email'=>'',
    'Subject'=>'Asunto',
    'Body'=>'Mensaje',
    'Verification Code'=>'Código de verificación',
);
