<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Activate' => '',
  'Create' => '',
  'Create profile field' => '',
  'Display order of fields.' => '',
  'Enter the activation code you recieved below.' => '',
  'If you failed to recieve the activation email, click the Resend Activation button.' => '',
  'List profile field' => '',
  'Login' => '',
  'Manage' => '',
  'Manage profile fields' => '',
  'Manage users' => '',
  'Profile' => '',
  'Profile field {fieldname}' => '',
  'Profile fields' => '',
  'Profile of ' => '',
  'Resend Activation' => '',
  'Update' => '',
  'Update profile field' => '',
  'User list' => '',
  'Users' => '',
);
