<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-25 at 22:49:42.
 */
class PostTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Post
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Post;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Post::model
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::scopes
     * @todo   Implement testScopes().
     */
    public function testScopes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getBlogPosts
     * @todo   Implement testGetBlogPosts().
     */
    public function testGetBlogPosts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::showCategoriesAsLabel
     * @todo   Implement testShowCategoriesAsLabel().
     */
    public function testShowCategoriesAsLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getCategoriesAsLabel
     * @todo   Implement testGetCategoriesAsLabel().
     */
    public function testGetCategoriesAsLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getPubDate
     * @todo   Implement testGetPubDate().
     */
    public function testGetPubDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getMarkdownBody
     * @todo   Implement testGetMarkdownBody().
     */
    public function testGetMarkdownBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::showUserAndDateAsLabel
     * @todo   Implement testShowUserAndDateAsLabel().
     */
    public function testShowUserAndDateAsLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::showUserAndDate
     * @todo   Implement testShowUserAndDate().
     */
    public function testShowUserAndDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Post::getUserAndDate
     * @todo   Implement testGetUserAndDate().
     */
    public function testGetUserAndDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
