<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Cronjob not installed' => '',
  'No description found for the requested cron job' => '',
  'You didn\'t set the cron table name' => '',
  'You have to provide a name for the cronjob' => '',
  'could not install the module. Lapse must be an integer' => '',
  'delete users who have not been activated for more then 7 days' => '',
  'installed and running' => '',
  'not installed' => '',
  'reactivate users whose ban period is over' => '',
  'the model provided is not an instance of CActiveRecord' => '',
  'the provided criteria are not an instance of CDbCriteria' => '',
  'you didn\'t initialize the UGCron singleton' => '',
  'you didn\'t provide a valid action' => '',
  'you didn\'t set the columns to update' => '',
);
