<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '<p>userGroups Installed! To continue the configuration please login</p><p>The new Controller class file has been created. Your old controller has been saved in the component folder with the name <i>_old_Controller.php</i></p>' => '',
  'Access Code' => '',
  'Error during installation. Couldn\'t create root group with id {id}' => '',
  'Error during installation. Couldn\'t create root user with id {id}' => '',
  'Password Reset: Question' => '',
  'Retype Root Password' => '',
  'Root Email' => '',
  'Root Password' => '',
  'Root User' => '',
  'Setting not installed. Installation abort.' => '',
  'The two access codes don\'t match.' => '',
  'Unable to create the tables in the database. Make sure that your db user has the necessary permissions to create a new table.<br/>This release only officially supports Mysql and PostgreSQL.' => '',
  'Unable to write the file {path}.' => '',
  'You didn\'t correctly set the class property in the user component.<br/>Value set: <b>{class}</b><br/>Value expected: <b>WebUserGroups</b>' => '',
  'You didn\'t set an adminEmail param inside your application configuration file.' => '',
  'You didn\'t set the access code in your config file.' => '',
  'for security reasons the root password must contain at least 2 digits and 2 letters' => '',
  'the Access Code cannot be blank' => '',
  'the confirmation password doesn\'t match the password' => '',
);
