<?php

/**
 * This is the model base class for the table "event_attendant".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventAttendant".
 *
 * Columns in table "event_attendant" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $event_id
 * @property integer $attendant_id
 * @property integer $event_attendant_status_id
 * @property integer $attended
 *
 */
abstract class BaseEventAttendant extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'event_attendant';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EventAttendant|EventAttendants', $n);
	}

	public static function representingColumn() {
		return array(
			'event_id',
			'attendant_id',
		);
	}

	public function rules() {
		return array(
			array('event_id, attendant_id, event_attendant_status_id', 'required'),
			array('event_id, attendant_id, event_attendant_status_id, attended', 'numerical', 'integerOnly'=>true),
			array('attended', 'default', 'setOnEmpty' => true, 'value' => null),
			array('event_id, attendant_id, event_attendant_status_id, attended', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'event_id' => null,
			'attendant_id' => null,
			'event_attendant_status_id' => null,
			'attended' => Yii::t('app', 'Attended'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('attendant_id', $this->attendant_id);
		$criteria->compare('event_attendant_status_id', $this->event_attendant_status_id);
		$criteria->compare('attended', $this->attended);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}