<?php

/**
 * This is the model base class for the table "sponsor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sponsor".
 *
 * Columns in table "sponsor" available as properties of the model,
 * followed by relations of table "sponsor" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Event[] $events
 */
abstract class BaseSponsor extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sponsor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sponsor|Sponsors', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>45),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'events' => array(self::MANY_MANY, 'Event', 'event_sponsor(sponsor_id, event_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'events' => 'EventSponsor',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'events' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}