<?php

/**
 * This is the model base class for the table "location".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Location".
 *
 * Columns in table "location" available as properties of the model,
 * followed by relations of table "location" available as properties of the model.
 *
 * @property integer $id
 * @property string $address
 *
 * @property Event[] $events
 * @property Organization[] $organizations
 */
abstract class BaseLocation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'location';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Location|Locations', $n);
	}

	public static function representingColumn() {
		return 'address';
	}

	public function rules() {
		return array(
			array('address', 'safe'),
			array('address', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, address', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'events' => array(self::HAS_MANY, 'Event', 'location_id'),
			'organizations' => array(self::HAS_MANY, 'Organization', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'address' => Yii::t('app', 'Address'),
			'events' => null,
			'organizations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('address', $this->address, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}