<?php

/**
 * This is the model base class for the table "person_organization".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonOrganization".
 *
 * Columns in table "person_organization" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $person_id
 * @property integer $organization_id
 * @property integer $position_id
 *
 */
abstract class BasePersonOrganization extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'person_organization';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonOrganization|PersonOrganizations', $n);
	}

	public static function representingColumn() {
		return array(
			'person_id',
			'organization_id',
		);
	}

	public function rules() {
		return array(
			array('person_id, organization_id', 'required'),
			array('person_id, organization_id, position_id', 'numerical', 'integerOnly'=>true),
			array('position_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('person_id, organization_id, position_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'person_id' => null,
			'organization_id' => null,
			'position_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('organization_id', $this->organization_id);
		$criteria->compare('position_id', $this->position_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}