<?php

/**
 * This is the model base class for the table "date".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Date".
 *
 * Columns in table "date" available as properties of the model,
 * followed by relations of table "date" available as properties of the model.
 *
 * @property integer $id
 * @property integer $event_id
 * @property string $start_date
 * @property string $end_date
 * @property string $start_time
 * @property string $end_time
 *
 * @property Event $event
 */
abstract class BaseDate extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'date';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Date|Dates', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('event_id, start_date', 'required'),
			array('event_id', 'numerical', 'integerOnly'=>true),
			array('start_date, end_date, start_time, end_time', 'length', 'max'=>45),
			array('end_date, start_time, end_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, event_id, start_date, end_date, start_time, end_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'event' => array(self::BELONGS_TO, 'Event', 'event_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'event_id' => null,
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'event' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('event_id', $this->event_id);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('start_time', $this->start_time, true);
		$criteria->compare('end_time', $this->end_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}