<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $title
 * @property string $body
 * @property string $status
 * @property integer $in_frontpage
 * @property string $created_at
 * @property string $publication_date
 * @property string $visits
 * @property integer $in_blog
 *
 * @property User $user
 * @property Category[] $categories
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, created_at', 'required'),
			array('user_id, in_frontpage, in_blog', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>200),
			array('status', 'length', 'max'=>45),
			array('visits', 'length', 'max'=>20),
			array('body, publication_date', 'safe'),
			array('user_id, body, status, in_frontpage, publication_date, visits, in_blog', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, title, body, status, in_frontpage, created_at, publication_date, visits, in_blog', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'categories' => array(self::MANY_MANY, 'Category', 'post_category(post_id, category_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'categories' => 'PostCategory',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'title' => Yii::t('app', 'Title'),
			'body' => Yii::t('app', 'Body'),
			'status' => Yii::t('app', 'Status'),
			'in_frontpage' => Yii::t('app', 'In Frontpage'),
			'created_at' => Yii::t('app', 'Created At'),
			'publication_date' => Yii::t('app', 'Publication Date'),
			'visits' => Yii::t('app', 'Visits'),
			'in_blog' => Yii::t('app', 'In Blog'),
			'user' => null,
			'categories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('in_frontpage', $this->in_frontpage);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('publication_date', $this->publication_date, true);
		$criteria->compare('visits', $this->visits, true);
		$criteria->compare('in_blog', $this->in_blog);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}