<?php

/**
 * This is the model base class for the table "attendant".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Attendant".
 *
 * Columns in table "attendant" available as properties of the model,
 * followed by relations of table "attendant" available as properties of the model.
 *
 * @property integer $id
 * @property integer $person_id
 *
 * @property Person $person
 * @property Event[] $events
 */
abstract class BaseAttendant extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'attendant';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Attendant|Attendants', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person_id', 'required'),
			array('person_id', 'numerical', 'integerOnly'=>true),
			array('id, person_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person' => array(self::BELONGS_TO, 'Person', 'person_id'),
			'events' => array(self::MANY_MANY, 'Event', 'event_attendant(attendant_id, event_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'events' => 'EventAttendant',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person_id' => null,
			'person' => null,
			'events' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person_id', $this->person_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}