<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => '',
  'Access' => '',
  'Account not active' => '',
  'Activate the account' => '',
  'An Error Occurred. Please try later.' => '',
  'An email containing the instructions to reset your password has been sent to your email address: {email}' => '',
  'An email was sent with the instructions to activate your account to the address {email}.' => '',
  'An invitation email was sent to the address {email}' => '',
  'Approve Registration' => '',
  'Ban User' => '',
  'Change Password' => '',
  'Confirm Password' => '',
  'Creation Date' => '',
  'Data Updated Successfully' => '',
  'Delete' => '',
  'Documentation' => '',
  'Edit Profile' => '',
  'Edit {username}\'s Profile' => '',
  'Email' => '',
  'Fields with {*} are required.' => '',
  'General Info' => '',
  'Group' => '',
  'Group Level' => '',
  'Group Name' => '',
  'Groups' => '',
  'Home' => '',
  'Impossible to send email to the address {email}' => '',
  'Invalid email address' => '',
  'Invite User' => '',
  'Level' => '',
  'Login Required' => '',
  'My Profile' => '',
  'Name' => '',
  'Old Password' => '',
  'Password' => '',
  'Password Reset: Answer' => '',
  'Password Reset: Question' => '',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => '',
  'Proceed' => '',
  'Recovery Mode' => '',
  'Register' => '',
  'Registration Complete, you can now login.' => '',
  'Registration Complete. You now have to wait for an admin to approve your account.' => '',
  'Remember Me' => '',
  'Request New Password' => '',
  'Resend Email' => '',
  'Root Tools' => '',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => '',
  'Save' => '',
  'Security' => '',
  'The activation email was successfully sent to {email}' => '',
  'The requested page does not exist.' => '',
  'This account is not approved yet' => '',
  'Update' => '',
  'Update External Profile' => '',
  'Update User' => '',
  'Update User Profile' => '',
  'User Invitation' => '',
  'User List' => '',
  'User Name' => '',
  'User Registration' => '',
  'Username' => '',
  'Users' => '',
  'Verification Code' => '',
  'We are sorry, but your account is banned' => '',
  'You are not allowed to update other accounts' => '',
  'You didn\'t enter the correct password' => '',
  'profile' => '',
  'register' => '',
  'the confirmation password doesn\'t match the password' => '',
  'the password must be of at least 5 characters' => '',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => '',
  'the password must contain at least 2 digits, 2 letters and a special character' => '',
  'username must be at least 4 characters and can only be alphanumeric' => '',
  '{username}\'s Profile' => '',
);
