<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'A problem occurred during the Data and Access Permission save action' => '',
  'A problem occurred during the configuration save action' => '',
  'A problem occurred during the cron jobs configuration save action' => '',
  'About the author' => '',
  'Ban Period' => '',
  'Ban Reason' => '',
  'Controller' => '',
  'Cron Jobs' => '',
  'Cron Jobs Configuration Saved' => '',
  'Cron Jobs successfully removed' => '',
  'Data and Access Permission of <i>{displayname} group</i> changed' => '',
  'Data and Access Permission of <i>{displayname} user</i> changed' => '',
  'Description' => '',
  'Do you really want to approve {who} registration?' => '',
  'Do you really want to ban {who}?' => '',
  'Do you really want to delete the group {group}?' => '',
  'Do you really want to delete the user {user}?' => '',
  'Do you really want to remove those CronJobs?' => '',
  'Documentation' => '',
  'Element' => '',
  'Email Customization' => '',
  'First Steps' => '',
  'Forever' => '',
  'Group Home: {home}' => '',
  'Group {groupname}: Data and Access Permissions' => '',
  'Impossible to delete the requested user/group. An Error Occurred' => '',
  'Invalid Request.' => '',
  'Is this thing safe?' => '',
  'Lapse' => '',
  'Last Execution' => '',
  'License' => '',
  'Localization' => '',
  'Main Configurations' => '',
  'Module' => '',
  'New Configurations Saved' => '',
  'New Group: Data and Access Permissions' => '',
  'New User: Data and Access Permissions' => '',
  'New group Created.' => '',
  'New user Created.' => '',
  'Options' => '',
  'Permission' => '',
  'Permission granted from Group' => '',
  'Profile Extensions' => '',
  'Remember if you delete a Group you\'ll delete all the users that belongs to it.' => '',
  'Remove not installed CronJobs' => '',
  'Root Tools' => '',
  'Setting' => '',
  'Setup the new accessControlFilter' => '',
  'Status' => '',
  'The following problems occurred: {errors}' => '',
  'The requested cron does not exist.' => '',
  'The requested rule does not exist.' => '',
  'The requested user/group does not exist and cannot be deleted.' => '',
  'This group does not exist' => '',
  'User {username}: Data and Access Permissions' => '',
  'Using the new Access Rules' => '',
  'Value' => '',
  'What\'s coming next?' => '',
  'What\'s new?' => '',
  'You are not allowed to change any configuration' => '',
  'You are not allowed to change the cron jobs configuration' => '',
  'You are not allowed to remove cron jobs' => '',
  'You cannot assign to a User a Group that has a Level equal or higher then the one you belong to' => '',
  'You cannot ban a user with a level higher then yours.' => '',
  'You cannot change constant values' => '',
  'You cannot change data or permissions of Root' => '',
  'You cannot change data or permissions of a user or a group with a level higher then yours' => '',
  'You cannot change the Access Permissions of the Root User' => '',
  'You cannot create a new user or group' => '',
  'You cannot delete a user/group with a higher level then yours.' => '',
  'You cannot set a Group Level equal or higher then Root' => '',
  'You cannot set a Group Level equal or superior to your own' => '',
  'You cannot set this value to a level equal or higher then your own' => '',
  'You didn\'t supply a valid id' => '',
  'You don\'t have the permission to delete any user/group' => '',
  'add group' => '',
  'add user' => '',
  'all' => '',
  'click here to return to the admin page' => '',
  'click here update userGroups' => '',
  'if you omit the password a random one will be generated' => '',
  'if you omit the username the user will be able to chose one upon activation of the account' => '',
  'invalid value' => '',
  'it was not possible to get the value of permissionControl inside your controller. Check your Controller.' => '',
  'update to version {version}' => '',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '',
  '{n} Day|{n} Days' => '',
  '{n} Month|{n} Months' => '',
  '{n} Week|{n} Weeks' => '',
  '{username}\'s account is banned untill {day}.' => '',
  '{username}\'s account is now active.' => '',
  '{what} deleted.' => '',
);
