<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '{attribute} is too long (max. {num} characters).' => '',
  '{attribute} is too short (min. {num} characters).' => '',
  '{attribute} must include at least {num} digits.' => '',
  '{attribute} must include at least {num} lower case letters.' => '',
  '{attribute} must include at least {num} symbols.' => '',
  '{attribute} must include at least {num} upper case letters.' => '',
  '{attribute} must not contain more than {num} sequentially repeated characters.' => '',
  '{attribute} must not contain whitespace.' => '',
);
